name: Get Tag Version Sample

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Increment version
        id: version
        run: |
          LATEST_TAG=$(git tag)
          echo "Latest tag: $LATEST_TAG"
