name: Get Tag Version Sample

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Increment version
        id: version
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
